Repository 9tigerio/db2rest, pull requests merged in 2024-02, with the labels that each got.

#233 #220 - refactor delete controller
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateRestApi.java
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateRestController.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteController.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteRestApi.java
Labels: enhancement

#238 fix implicit inner join
  src/main/java/com/homihq/db2rest/mybatis/MyBatisTable.java
  src/main/java/com/homihq/db2rest/rest/read/helper/JoinBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/SelectBuilder.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
Labels: bug

#239 Feature/183 return generated key for insert
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateController.java
  src/main/java/com/homihq/db2rest/rest/create/CreateController.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/main/java/com/homihq/db2rest/rest/create/dto/CreateBulkResponse.java
  src/main/java/com/homihq/db2rest/rest/create/dto/CreateResponse.java
  src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
Labels: enhancement

#249 refactor to new version of query engine.
  src/main/java/com/homihq/db2rest/rest/read/helper/JoinBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/v2/ReadControllerV2.java
  src/main/java/com/homihq/db2rest/rest/read/v2/ReadServiceV2.java
  src/main/java/com/homihq/db2rest/rest/read/v2/dto/ReadContextV2.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/ReadProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/RootFieldProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/RootTableProcessor.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
  src/main/java/com/homihq/db2rest/schema/TypeMapperUtil.java
Labels: enhancement

#250 Feature/refactor query 2
  src/main/java/com/homihq/db2rest/mybatis/MyBatisTable.java
  src/main/java/com/homihq/db2rest/rest/read/helper/ReadContext.java
  src/main/java/com/homihq/db2rest/rest/read/v2/ReadControllerV2.java
  src/main/java/com/homihq/db2rest/rest/read/v2/ReadServiceV2.java
  src/main/java/com/homihq/db2rest/rest/read/v2/dto/JoinDetail.java
  src/main/java/com/homihq/db2rest/rest/read/v2/dto/ReadContextV2.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/QueryCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/ReadPreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/RootFieldPreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/RootTablePreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/RootWhereProcessor.java
  src/main/java/com/homihq/db2rest/rsql/operators/Operator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/EqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/InOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/NotInOperator.java
  src/main/java/com/homihq/db2rest/rsql/parser/MyBatisFilterVisitor.java
  src/main/java/com/homihq/db2rest/schema/TypeMapperUtil.java
  src/main/java/com/homihq/db2rest/type/JdbcDataTypeConverter.java
Labels: enhancement

#252 #251 moved custom query to separate class - SRP principle
  src/main/java/com/homihq/db2rest/rest/read/CustomQueryController.java
  src/main/java/com/homihq/db2rest/rest/read/CustomQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/ReadController.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
Labels: enhancement

#255 #254 refactor find one query
  src/main/java/com/homihq/db2rest/rest/read/FindOneController.java
  src/main/java/com/homihq/db2rest/rest/read/FindOneService.java
  src/main/java/com/homihq/db2rest/rest/read/ReadController.java
Labels: enhancement

#260 #259 - add limit and offset
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/QueryCreatorTemplate.java
Labels: enhancement

#264 Feature/join re design
  src/main/java/com/homihq/db2rest/exception/InvalidOperatorException.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/rest/read/ReadController.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/helper/JoinBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/WhereBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/v2/dto/JoinDetail.java
  src/main/java/com/homihq/db2rest/rest/read/v2/dto/ReadContextV2.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/QueryCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/post/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/post/ReadPostProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/pre/ReadPreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/pre/RootFieldPreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/pre/RootTablePreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/pre/RootWhereProcessor.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
  src/main/java/com/homihq/db2rest/rsql/operators/RSQLOperatorHandlers.java
  src/main/java/com/homihq/db2rest/rsql/parser/JoinOnParser.java
  src/main/java/com/homihq/db2rest/rsql/parser/MyBatisFilterVisitorParser.java
  src/main/resources/application.yml
Labels: enhancement

#265 add join table columns in projection
  src/main/java/com/homihq/db2rest/rest/read/ReadController.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/dto/JoinDetail.java
  src/main/java/com/homihq/db2rest/rest/read/dto/ReadContextV2.java
  src/main/java/com/homihq/db2rest/rest/read/helper/ProjectionBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/processor/QueryCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rest/read/processor/post/JoinPostProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/post/OrderByPostProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/post/ReadPostProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/pre/JoinTableFieldPreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/pre/ReadPreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/pre/RootTableFieldPreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/pre/RootTablePreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/pre/RootWhereProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/v2/processor/pre/ReadPreProcessor.java
Labels: enhancement

#269 Feature/266 compound join
  pom.xml
  src/main/java/com/homihq/db2rest/config/ThymeleafConfiguration.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/dto/JoinDetail.java
  src/main/java/com/homihq/db2rest/rest/read/dto/ReadContextV2.java
  src/main/java/com/homihq/db2rest/rest/read/helper/TableUtil.java
  src/main/java/com/homihq/db2rest/rest/read/helper/WhereBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/model/DbColumn.java
  src/main/java/com/homihq/db2rest/rest/read/model/DbTable.java
  src/main/java/com/homihq/db2rest/rest/read/model/DbWhere.java
  src/main/java/com/homihq/db2rest/rest/read/processor/QueryCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rest/read/processor/post/JoinPostProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/pre/JoinTableFieldPreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/pre/RootTableFieldPreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/pre/RootTablePreProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/pre/RootWhereProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/CustomRSQLOperators.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/EndWithOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/EqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/GreaterThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/GreaterThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/InOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/LessThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/LessThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/LikeOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/NotEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/NotInOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/OperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/RSQLOperatorHandlers.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/StartWithOperatorHandler.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/parser/RSQLParserBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/visitor/BaseRSQLVisitor.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
  src/main/java/com/homihq/db2rest/rsql/operators/RSQLOperatorHandlers.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/Operator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/RSQLOperatorHandlers.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/SimpleRSQLOperators.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/EndWithOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/EqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/GreaterThanEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/GreaterThanOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/InOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/LessThanEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/LessThanOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/LikeOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/NotEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/NotInOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/StartWithOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/parser/JoinOnParser.java
  src/main/java/com/homihq/db2rest/rsql/v1/parser/WhereFilterVisitor.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
  src/main/java/com/homihq/db2rest/template/SqlRenderer.java
  src/main/resources/sql-templates/read.sql
Labels: enhancement

#274 #272 - fixed column alias
  src/main/java/com/homihq/db2rest/exception/GlobalExceptionHandler.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/helper/TableUtil.java
  src/main/java/com/homihq/db2rest/rest/read/model/DbColumn.java
  src/main/java/com/homihq/db2rest/rest/read/model/DbTable.java
  src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/QueryCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rsql/v1/parser/JoinOnParser.java
  src/main/java/com/homihq/db2rest/schema/dialect/MySQL.java
Labels: bug

#277 #276 - refactor delete to remove mybatis dynamic by template based sq…
  src/main/java/com/homihq/db2rest/model/DbAlias.java
  src/main/java/com/homihq/db2rest/model/DbColumn.java
  src/main/java/com/homihq/db2rest/model/DbJoin.java
  src/main/java/com/homihq/db2rest/model/DbTable.java
  src/main/java/com/homihq/db2rest/model/DbWhere.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteController.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteRestApi.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/rest/delete/dto/DeleteContext.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/dto/ReadContextV2.java
  src/main/java/com/homihq/db2rest/rest/read/helper/SortBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/TableUtil.java
  src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/QueryCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootTableFieldProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootTableProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootWhereProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/rsql/operator/handler/RSQLOperatorHandlers.java
  src/main/java/com/homihq/db2rest/rsql2/operator/CustomRSQLOperators.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/EndWithOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/EqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/GreaterThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/GreaterThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/InOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/LessThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/LessThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/LikeOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/NotEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/NotInOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/OperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/OperatorMap.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/RSQLOperatorHandlers.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/StartWithOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/parser/RSQLParserBuilder.java
  src/main/java/com/homihq/db2rest/rsql2/visitor/BaseRSQLVisitor.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
  src/main/resources/application.yml
  src/main/resources/sql-templates/delete.sql
Labels: enhancement

#278 #275 - support for pagination
  src/main/java/com/homihq/db2rest/rest/read/processor/QueryCreatorTemplate.java
  src/main/resources/application.yml
  src/main/resources/sql-templates/read.sql
Labels: enhancement

#280 #261 - sort processing
  src/main/java/com/homihq/db2rest/model/DbSort.java
  src/main/java/com/homihq/db2rest/rest/read/ReadController.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/dto/ReadContext.java
  src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/OrderByProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/QueryCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rest/read/processor/ReadProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootTableFieldProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootTableProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootWhereProcessor.java
  src/main/resources/sql-templates/read.sql
Labels: enhancement

#284 #282 - updated tsid design doc
  design/insert.md
Labels: documentation

#287 #286 - type conversion error
  src/main/java/com/homihq/db2rest/dialect/Dialect.java
  src/main/java/com/homihq/db2rest/dialect/MySQLDialect.java
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootWhereProcessor.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/EndWithOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/EqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/GreaterThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/GreaterThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/InOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/LessThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/LessThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/LikeOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/NotEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/NotInOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/OperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/operator/handler/StartWithOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql2/visitor/BaseRSQLVisitor.java
Labels: bug

#290 #227 - support timestamp for mysql and postgresql
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
Labels: enhancement

#291 #216 - support json column support
  src/main/java/com/homihq/db2rest/dialect/MySQLDialect.java
Labels: enhancement

#292 #202 - mysql view support
  src/main/java/com/homihq/db2rest/dialect/Dialect.java
  src/main/java/com/homihq/db2rest/dialect/MySQLDialect.java
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
Labels: enhancement

#293 #232 - timestampz support
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
Labels: enhancement

#294 #231 - timetz support
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
Labels: enhancement

#295 bulk insert columns support
  README.md
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
  src/main/java/com/homihq/db2rest/rest/create/tsid/TSIDProcessor.java
Labels: enhancement

#297 #296 - cleanup schema dependency and mybatis for update
  src/main/java/com/homihq/db2rest/dialect/Dialect.java
  src/main/java/com/homihq/db2rest/rest/delete/dto/DeleteContext.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateController.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
  src/main/java/com/homihq/db2rest/rest/update/dto/UpdateContext.java
  src/main/resources/application.yml
  src/main/resources/sql-templates/update.sql
Labels: enhancement

#298 #272 - fix bulk upload
  pom.xml
  src/main/java/com/homihq/db2rest/Db2restApplication.java
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
  src/main/java/com/homihq/db2rest/rest/create/bulk/CSVDataProcessor.java
  src/main/java/com/homihq/db2rest/rest/create/bulk/JSONDataProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/helper/AliasGenerator.java
Labels: enhancement

#299 #206 - added support for materialized view for postgresql
  src/main/java/com/homihq/db2rest/schema/AliasGenerator.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
Labels: enhancement

#305 #304 - fix pg sql insert keys issue.
  src/main/java/com/homihq/db2rest/model/DbTable.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
Labels: enhancement

#307 #306 - fix save error response
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
  src/main/java/com/homihq/db2rest/exception/GlobalExceptionHandler.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
Labels: bug

#309 #308 - improve error reporting
  src/main/java/com/homihq/db2rest/exception/InvalidColumnException.java
  src/main/java/com/homihq/db2rest/exception/InvalidTableException.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
Labels: enhancement

#310 Feature/302 refactor mybatis
  README.md
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
  src/main/java/com/homihq/db2rest/rest/read/CountQueryController.java
  src/main/java/com/homihq/db2rest/rest/read/CountQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootTableFieldProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/sql/QueryCreatorTemplate.java
  src/main/resources/sql-templates/count.sql
Labels: enhancement

#312 Feature/302 further refactor mybatis
  README.md
  pom.xml
  src/main/java/com/homihq/db2rest/mybatis/DB2RestRenderingStrategy.java
  src/main/java/com/homihq/db2rest/mybatis/MyBatisTable.java
  src/main/java/com/homihq/db2rest/rest/read/CustomQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/FindOneController.java
  src/main/java/com/homihq/db2rest/rest/read/FindOneService.java
  src/main/java/com/homihq/db2rest/rest/read/dto/FindOneResponse.java
  src/main/java/com/homihq/db2rest/rest/read/helper/JoinBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/LimitPaginationBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/ReadContext.java
  src/main/java/com/homihq/db2rest/rest/read/helper/SelectBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/SortBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/TableUtil.java
  src/main/java/com/homihq/db2rest/rest/read/helper/WhereBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/sql/QueryCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/Operator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/RSQLOperatorHandlers.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/SimpleRSQLOperators.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/EndWithOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/EqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/GreaterThanEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/GreaterThanOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/InOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/LessThanEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/LessThanOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/LikeOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/NotEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/NotInOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/operators/handler/StartWithOperator.java
  src/main/java/com/homihq/db2rest/rsql/v1/parser/WhereFilterVisitor.java
  src/main/java/com/homihq/db2rest/schema/NameUtil.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
  src/main/java/com/homihq/db2rest/schema/TypeMapperUtil.java
  src/main/resources/sql-templates/find-one.sql
Labels: enhancement

#314 Feature/182 exists query support
  src/main/java/com/homihq/db2rest/rest/read/ExistsQueryController.java
  src/main/java/com/homihq/db2rest/rest/read/ExistsQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/dto/ExistsResponse.java
  src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/sql/QueryCreatorTemplate.java
  src/main/resources/sql-templates/exists.sql
Labels: enhancement

#317 Feature/300 fix integration test
  pom.xml
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
  src/main/java/com/homihq/db2rest/model/DbColumn.java
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
  src/main/java/com/homihq/db2rest/rest/create/CreateController.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/main/java/com/homihq/db2rest/rest/create/tsid/TSIDProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/FindOneService.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
  src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLDeleteControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLUpdateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgDeleteControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgUpdateControllerTest.java
  src/test/resources/mysql/mysql-sakila.sql
  src/test/resources/pg/postgres-sakila.sql
  src/test/resources/testdata/BULK_RESULT_ACTOR_QUERY.json
  src/test/resources/testdata/CREATE_DIRECTOR_REQUEST.json
  src/test/resources/testdata/CREATE_FILM_REQUEST.json
  src/test/resources/testdata/CREATE_FILM_REQUEST_ERROR.json
  src/test/resources/testdata/CREATE_FILM_REQUEST_MISSING_PAYLOAD.json
  src/test/resources/testdata/CREATE_VANITY_VAN_REQUEST.json
  src/test/resources/testdata/EMPTY_ACTOR_QUERY.json
  src/test/resources/testdata/SINGLE_RESULT_ACTOR_QUERY.json
Labels: enhancement

#318 #316 - remove spring data
  pom.xml
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateController.java
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
Labels: enhancement

#320 #316 - fix unkey imports
  src/main/java/com/homihq/db2rest/auth/unkey/UnKeyAuthFilter.java
Labels: bug

#323 refactoring schema manager
  src/main/java/com/homihq/db2rest/model/DbTable.java
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootTableProcessor.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
Labels: enhancement

#324 refactoring db operation
  src/main/java/com/homihq/db2rest/dbop/JdbcOperationService.java
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/rest/read/CountQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/CustomQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/ExistsQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/FindOneService.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/dto/QueryRequest.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
Labels: enhancement

#325 refactoring db operation
  src/main/java/com/homihq/db2rest/config/JdbcConfiguration.java
  src/main/java/com/homihq/db2rest/dbop/JdbcOperationService.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootWhereProcessor.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
  src/main/java/com/homihq/db2rest/rsql/operator/CustomRSQLOperators.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/EndWithOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/EqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/GreaterThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/GreaterThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/InOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/LessThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/LessThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/LikeOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/NotEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/NotInOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/OperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/OperatorMap.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/RSQLOperatorHandlers.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/StartWithOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/parser/RSQLParserBuilder.java
  src/main/java/com/homihq/db2rest/rsql/visitor/BaseRSQLVisitor.java
Labels: enhancement

#326 #322 - paving way for d1 operations
  src/main/java/com/homihq/db2rest/Db2restApplication.java
  src/main/java/com/homihq/db2rest/config/JdbcConfiguration.java
  src/main/java/com/homihq/db2rest/dbop/D1OperationService.java
  src/main/java/com/homihq/db2rest/dbop/DbOperationService.java
  src/main/java/com/homihq/db2rest/dbop/JdbcOperationService.java
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/rest/read/CountQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/CustomQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/ExistsQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/FindOneService.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootTableProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootWhereProcessor.java
  src/main/java/com/homihq/db2rest/rest/rpc/FunctionController.java
  src/main/java/com/homihq/db2rest/rest/rpc/FunctionService.java
  src/main/java/com/homihq/db2rest/rest/rpc/ProcedureController.java
  src/main/java/com/homihq/db2rest/rest/rpc/ProcedureService.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
  src/main/java/com/homihq/db2rest/schema/D1SchemaManager.java
  src/main/java/com/homihq/db2rest/schema/JdbcSchemaManager.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
  src/main/resources/application.yml
  src/test/resources/application-it.yaml
Labels: enhancement

#327 Feature/322 retrieve d1 meta data
  src/main/java/com/homihq/db2rest/auth/unkey/UnKeyAuthConfiguration.java
  src/main/java/com/homihq/db2rest/d1/D1Configuration.java
  src/main/java/com/homihq/db2rest/d1/D1RestClient.java
  src/main/java/com/homihq/db2rest/d1/model/D1Column.java
  src/main/java/com/homihq/db2rest/d1/model/D1PostRequest.java
  src/main/java/com/homihq/db2rest/d1/model/D1PostResponse.java
  src/main/java/com/homihq/db2rest/d1/model/D1Result.java
  src/main/java/com/homihq/db2rest/d1/model/D1Table.java
  src/main/java/com/homihq/db2rest/d1/model/Message.java
  src/main/java/com/homihq/db2rest/dialect/MySQLDialect.java
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
  src/main/java/com/homihq/db2rest/model/DbColumn.java
  src/main/java/com/homihq/db2rest/model/DbTable.java
  src/main/java/com/homihq/db2rest/rest/create/CreateCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rest/create/tsid/TSIDProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rsql/visitor/BaseRSQLVisitor.java
  src/main/java/com/homihq/db2rest/schema/D1SchemaManager.java
  src/main/java/com/homihq/db2rest/schema/JdbcSchemaManager.java
  src/main/resources/application.yml
Labels: enhancement

#328 Feature/322 prepare query
  README.md
  pom.xml
  src/main/java/com/homihq/db2rest/d1/D1Configuration.java
  src/main/java/com/homihq/db2rest/d1/D1RestClient.java
  src/main/java/com/homihq/db2rest/d1/D1SchemaManager.java
  src/main/java/com/homihq/db2rest/dbop/D1OperationService.java
  src/main/java/com/homihq/db2rest/dialect/D1Dialect.java
  src/main/java/com/homihq/db2rest/dialect/Dialect.java
  src/main/java/com/homihq/db2rest/dialect/MySQLDialect.java
  src/main/java/com/homihq/db2rest/dialect/PostGreSQLDialect.java
  src/main/java/com/homihq/db2rest/jdbc/JdbcOperationService.java
  src/main/java/com/homihq/db2rest/jdbc/JdbcSchemaManager.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcComponentConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcDataSourceConfiguration.java
  src/main/java/com/homihq/db2rest/model/DbColumn.java
  src/main/java/com/homihq/db2rest/model/DbTable.java
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateService.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/main/java/com/homihq/db2rest/rest/create/tsid/TSIDProcessor.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rest/read/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/rest/read/processor/RootTableFieldProcessor.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateCreatorTemplate.java
  src/main/java/com/homihq/db2rest/rsql/operator/handler/EqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/rsql/visitor/BaseRSQLVisitor.java
  src/main/java/com/homihq/db2rest/schema/D1SchemaManager.java
  src/main/java/com/homihq/db2rest/schema/TypeMapperUtil.java
  src/main/java/com/homihq/db2rest/type/JdbcDataTypeConverter.java
  src/main/resources/sql-templates/update.sql
Labels: enhancement
