Repository 9tigerio/db2rest, pull requests merged in 2024-11, with the labels that each got.

#741 fix issues within application.yml file
  api-rest/src/main/resources/application.yml
Labels: bug

#773 #772 - fix database metadata loading issues.
  api-rest/src/main/java/com/homihq/db2rest/jdbc/config/JdbcConfiguration.java
  api-rest/src/test/java/com/homihq/db2rest/jdbc/rest/meta/db/DbInfoControllerIntegrationTest.java
  rest-common/src/main/java/com/homihq/db2rest/multidb/DatabaseConnectionDetail.java
  rest-common/src/main/java/com/homihq/db2rest/multidb/DatabaseProperties.java
Labels: bug

#782 Add comments to dockerhub-publish.yml
  .github/workflows/dockerhub-publish.yml
Labels: documentation

#783 Update POMs and add Snapshot workflow
  .github/workflows/snapshot.yml
  README.md
  api-rest/pom-oracle9i.xml
  api-rest/pom.xml
  auth/pom.xml
  db2rest-common/pom.xml
  mariadb-dialect/pom.xml
  mongo-support/pom.xml
  mssql-dialect/pom.xml
  mysql-dialect/pom.xml
  oracle-dialect/pom.xml
  oracle9i-dialect/pom.xml
  pg-dialect/pom.xml
  pom.xml
  rdbms-common/pom.xml
  rdbms-spring-boot-starter/pom.xml
  rdbms-support/pom.xml
  rest-common/pom.xml
Labels: CI/CD

#808 quite the warnings for missing Javadocs
  pom.xml
Labels: CI/CD
