Repository 9tigerio/db2rest, pull requests merged in 2024-01, with the labels that each got.

#86 Feature/refactor 1
  pom.xml
  src/main/java/com/homihq/db2rest/MyBatisDynamic.java
  src/main/java/com/homihq/db2rest/mybatis/DB2RTable.java
  src/main/java/com/homihq/db2rest/mybatis/DB2RestRenderingStrategy.java
  src/main/java/com/homihq/db2rest/rest/create/SaveResource.java
  src/main/java/com/homihq/db2rest/rest/create/SaveService.java
  src/main/java/com/homihq/db2rest/rest/query/QueryService.java
  src/main/java/com/homihq/db2rest/rest/query/helper/JoinBuilder.java
  src/main/java/com/homihq/db2rest/rest/query/helper/QueryBuilderContext.java
  src/main/java/com/homihq/db2rest/rest/query/helper/SelectBuilder.java
  src/main/java/com/homihq/db2rest/rest/query/helper/SqlQueryPartBuilder.java
  src/main/java/com/homihq/db2rest/rest/query/helper/WhereBuilder.java
  src/main/java/com/homihq/db2rest/rest/query/model/RColumn.java
  src/main/java/com/homihq/db2rest/rest/query/model/RCondition.java
  src/main/java/com/homihq/db2rest/rest/query/model/RJoin.java
  src/main/java/com/homihq/db2rest/rest/query/model/RTable.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/Operator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/RSQLOperatorHandlers.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/SimpleRSQLOperators.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/EndWithOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/EqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/GreaterThanEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/GreaterThanOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/InOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/LessThanEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/LessThanOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/LikeOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/NotEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/NotInOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/StartWithOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/parser/DefaultRSQLVisitorV2.java
  src/main/java/com/homihq/db2rest/schema/NameUtil.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
  src/main/java/com/homihq/db2rest/schema/dialect/MySQL.java
  src/main/resources/application.yml
Labels: enhancement

#91 Update README.md
  README.md
Labels: documentation

#92 Feature/90 remove jooq select
  src/main/java/com/homihq/db2rest/MyBatisDynamic.java
  src/main/java/com/homihq/db2rest/mybatis/DB2RTable.java
  src/main/java/com/homihq/db2rest/mybatis/MyBatisTable.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/rest/query/QueryService.java
  src/main/java/com/homihq/db2rest/rest/query/helper/JoinBuilder.java
  src/main/java/com/homihq/db2rest/rest/query/helper/QueryBuilderContext.java
  src/main/java/com/homihq/db2rest/rest/query/helper/SelectBuilder.java
  src/main/java/com/homihq/db2rest/rest/query/helper/SqlQueryPartBuilder.java
  src/main/java/com/homihq/db2rest/rest/query/helper/WhereBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/ReadController.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/helper/JoinBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/LimitPaginationBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/ReadContext.java
  src/main/java/com/homihq/db2rest/rest/read/helper/SelectBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/SortBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/WhereBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/model/JoinTable.java
  src/main/java/com/homihq/db2rest/rest/read/model/RColumn.java
  src/main/java/com/homihq/db2rest/rest/read/model/RCondition.java
  src/main/java/com/homihq/db2rest/rest/read/model/RJoin.java
  src/main/java/com/homihq/db2rest/rest/read/model/RTable.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/Operator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/EndWithOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/EqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/GreaterThanEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/GreaterThanOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/InOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/LessThanEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/LessThanOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/LikeOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/NotEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/NotInOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/operators/handler/StartWithOperator.java
  src/main/java/com/homihq/db2rest/rsql/v2/parser/BaseRSQLVisitor.java
  src/main/java/com/homihq/db2rest/rsql/v2/parser/MyBatisFilterVisitor.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
  src/main/java/com/homihq/db2rest/schema/SchemaService.java
Labels: enhancement

#95 #87 - remove jooq from delete
  src/main/java/com/homihq/db2rest/rest/delete/DeleteController.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
Labels: enhancement

#94 Update README.md
  README.md
Labels: documentation

#96 remove jooq dependency from update
  src/main/java/com/homihq/db2rest/config/JOOQConfiguration.java
  src/main/java/com/homihq/db2rest/rest/create/SaveController.java
  src/main/java/com/homihq/db2rest/rest/read/model/JoinTable.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateController.java
  src/main/java/com/homihq/db2rest/rest/update/UpdateService.java
  src/main/java/com/homihq/db2rest/rsql/v2/parser/BaseRSQLVisitor.java
Labels: enhancement

#107 #106 - rest docs added, restassured removed, will use webmvcmock
  FILTER.md
  pom.xml
  src/test/java/com/homihq/db2rest/BaseIntegrationTest.java
  src/test/java/com/homihq/db2rest/Db2restApplicationTests.java
  src/test/java/com/homihq/db2rest/MySQLBaseIntegrationTest.java
  src/test/java/com/homihq/db2rest/PostgreSQLBaseIntegrationTest.java
  src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
  src/test/java/com/homihq/db2rest/rest/ReadControllerTest.java
Labels: enhancement

#110 #108 - restdocs now configured to generate markdown
  src/test/java/com/homihq/db2rest/BaseIntegrationTest.java
Labels: enhancement

#111 #109 - testing github action for integration tests and build
  .github/workflows/ci-build.yml
Labels: enhancement

#118 #98 - update based on tests
  src/main/java/com/homihq/db2rest/mybatis/DB2RestRenderingStrategy.java
  src/main/java/com/homihq/db2rest/rest/create/CreateController.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/main/java/com/homihq/db2rest/rest/create/dto/CreateBulkResponse.java
  src/main/java/com/homihq/db2rest/rest/create/dto/CreateResponse.java
  src/main/resources/application.yml
Labels: enhancement

#121 adding integration test support with Test container for MySQL
  src/test/java/com/homihq/db2rest/BaseIntegrationTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
Labels: enhancement

#122 #105 - added multiple script files.
  src/test/java/com/homihq/db2rest/MySQLBaseIntegrationTest.java
  src/test/java/com/homihq/db2rest/PostgreSQLBaseIntegrationTest.java
  src/test/resources/mysql/mysql-sakila-insert-data.sql
  src/test/resources/mysql/mysql-sakila-schema.sql
  src/test/resources/pg/postgres-sakila-insert-data.sql
  src/test/resources/pg/postgres-sakila-schema.sql
Labels: enhancement

#126 #116 - integration test added for postgresql insert error.
  src/main/java/com/homihq/db2rest/exception/GenericDataAccessException.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
Labels: enhancement

#127 #76 - docker documentation added.
  README.md
Labels: documentation

#129 Fix typos and add clarity to README
  README.md
Labels: documentation

#138 #136 - ading integration test for bulk insert for postgresql
  src/test/java/com/homihq/db2rest/rest/MySQLCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
Labels: verification

#139 #135 - mysql bulk insert, minor other fixes
  src/test/java/com/homihq/db2rest/MySQLBaseIntegrationTest.java
  src/test/java/com/homihq/db2rest/PostgreSQLBaseIntegrationTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
Labels: verification

#152 added tsid for bulk creation and tests
  src/main/java/com/homihq/db2rest/rest/create/CreateController.java
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
  src/test/resources/mysql/mysql-sakila.sql
  src/test/resources/pg/postgres-sakila.sql
Labels: enhancement

#160 #151 - csv bulk upload added.
  pom.xml
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateController.java
  src/main/java/com/homihq/db2rest/rest/create/CreateController.java
  src/main/java/com/homihq/db2rest/rest/create/bulk/CSVDataProcessor.java
  src/main/java/com/homihq/db2rest/rest/create/bulk/DataProcessor.java
  src/main/java/com/homihq/db2rest/rest/create/bulk/JSONDataProcessor.java
  src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
Labels: enhancement

#161 #154 - simplification of installer
  src/main/java/com/homihq/db2rest/rest/create/bulk/CSVDataProcessor.java
  src/main/resources/application.yml
Labels: enhancement

#163 Feature/issue 11
  src/main/java/com/homihq/db2rest/rest/read/CountQueryController.java
  src/main/java/com/homihq/db2rest/rest/read/CountQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/ReadController.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/helper/ReadContext.java
  src/main/java/com/homihq/db2rest/rest/read/helper/SelectBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/model/CountResponse.java
  src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
Labels: enhancement

#167 mysql functions are now being created
  src/main/java/com/homihq/db2rest/rest/read/CountQueryController.java
  src/main/java/com/homihq/db2rest/rest/read/CountQueryService.java
  src/main/java/com/homihq/db2rest/rest/read/ReadController.java
  src/main/java/com/homihq/db2rest/rest/read/ReadService.java
  src/main/java/com/homihq/db2rest/rest/read/dto/CountResponse.java
  src/main/java/com/homihq/db2rest/rest/read/dto/QueryRequest.java
  src/main/java/com/homihq/db2rest/rest/read/model/QueryRequest.java
  src/test/java/com/homihq/db2rest/MySQLContainerConfiguration.java
  src/test/resources/mysql/mysql-sakila.sql
  src/test/resources/pg/postgres-sakila.sql
Labels: enhancement

#168 fix #162 - fix sort issue
  src/main/java/com/homihq/db2rest/rest/read/helper/ReadContext.java
  src/main/java/com/homihq/db2rest/rest/read/helper/SortBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/TableUtil.java
  src/main/java/com/homihq/db2rest/rest/read/model/DbAlias.java
  src/main/java/com/homihq/db2rest/rest/read/model/DbColumn.java
  src/main/java/com/homihq/db2rest/rest/read/model/DbTable.java
Labels: bug

#171 #169 - resolving multi join.
  src/main/java/com/homihq/db2rest/mybatis/MyBatisTable.java
  src/main/java/com/homihq/db2rest/rest/read/helper/JoinBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/ProjectionBuilder.java
  src/main/java/com/homihq/db2rest/rest/read/helper/ReadContext.java
  src/main/java/com/homihq/db2rest/rest/read/helper/SelectBuilder.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
Labels: bug, enhancement

#189 Feature/188 bulk csv json
  src/main/java/com/homihq/db2rest/rest/create/CreateService.java
  src/main/java/com/homihq/db2rest/rest/create/bulk/CSVDataProcessor.java
  src/main/java/com/homihq/db2rest/rest/create/bulk/DataProcessor.java
  src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
Labels: enhancement

#196 fix tests due to change of http status for delete success to 204
  src/main/java/com/homihq/db2rest/config/Db2RestConfigProperties.java
  src/main/java/com/homihq/db2rest/config/MultiTenancy.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteController.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/schema/SchemaManager.java
  src/test/java/com/homihq/db2rest/rest/MySQLDeleteAllTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLDeleteControllerTest.java
Labels: enhancement

#198 #197 - fix integer type
  pom.xml
  src/main/java/com/homihq/db2rest/jdbc/JdbcDataTypeConverter.java
  src/main/java/com/homihq/db2rest/mybatis/MyBatisTable.java
  src/main/java/com/homihq/db2rest/rest/delete/DeleteService.java
  src/main/java/com/homihq/db2rest/rsql/operators/Operator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/EndWithOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/EqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/GreaterThanEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/GreaterThanOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/InOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/LessThanEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/LessThanOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/LikeOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/NotEqualToOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/NotInOperator.java
  src/main/java/com/homihq/db2rest/rsql/operators/handler/StartWithOperator.java
  src/main/java/com/homihq/db2rest/rsql/parser/MyBatisFilterVisitor.java
  src/test/java/com/homihq/db2rest/rest/MySQLBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLDeleteControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLFunctionControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLProcedureControllerTest.java
  src/test/java/com/homihq/db2rest/rest/MySQLReadControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgFunctionControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgProcedureControllerTest.java
  src/test/java/com/homihq/db2rest/rest/PgReadControllerTest.java
Labels: bug

#210 #200 - upgrade to spring boot 3.2.2
  pom.xml
Labels: enhancement

#214 #213 - refactored create controller
  src/main/java/com/homihq/db2rest/rest/create/CreateController.java
  src/main/java/com/homihq/db2rest/rest/create/CreateRestApi.java
Labels: enhancement

#219 #215 - refactored bulk create controller
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateApi.java
  src/main/java/com/homihq/db2rest/rest/create/BulkCreateController.java
Labels: enhancement

#226 #224 - fixed now if select is not specified all columns of the root table is returned.
  src/main/java/com/homihq/db2rest/mybatis/MyBatisTable.java
  src/main/java/com/homihq/db2rest/rest/read/helper/ReadContext.java
  src/main/java/com/homihq/db2rest/rest/read/helper/SelectBuilder.java
Labels: bug
