Repository 9tigerio/db2rest, pull requests merged in 2024-04, with the labels that each got.

#405 #401 - add oracle delete tests
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLDeleteAllTest.java
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLDeleteControllerTest.java
  src/test/java/com/homihq/db2rest/rest/oracle/OracleCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/oracle/OracleDeleteAllTest.java
  src/test/java/com/homihq/db2rest/rest/oracle/OracleDeleteControllerTest.java
  src/test/resources/oracle/oracle-sakila-data.sql
Labels: enhancement, tests

#406 #402 - update tests for oracle
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLUpdateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/oracle/OracleUpdateControllerTest.java
Labels: enhancement, tests

#407 #403 - left and right join
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLBasicJoinControllerTest.java
  src/test/java/com/homihq/db2rest/rest/oracle/OracleBasicJoinControllerTest.java
  src/test/resources/oracle/oracle-sakila-data.sql
  src/test/resources/oracle/oracle-sakila.sql
  src/test/resources/testdata/LEFT_JOIN_ORACLE.json
  src/test/resources/testdata/RIGHT_JOIN_ORACLE.json
Labels: enhancement, tests

#413 #410 - inner join oracle
  src/test/java/com/homihq/db2rest/rest/oracle/OracleInnerJoinControllerTest.java
  src/test/resources/oracle/oracle-sakila-data.sql
  src/test/resources/oracle/oracle-sakila.sql
  src/test/resources/testdata/INNER_JOIN_ORACLE.json
Labels: enhancement, tests

#414 #412 - inner join with multiple tables
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLInnerJoinControllerTest.java
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLInnerJoinMultiTableControllerTest.java
  src/test/java/com/homihq/db2rest/rest/oracle/OracleInnerJoinMultiTableControllerTest.java
  src/test/resources/oracle/oracle-sakila-data.sql
  src/test/resources/oracle/oracle-sakila.sql
  src/test/resources/testdata/INNER_JOIN_MULTI_TABLE_ORACLE.json
Labels: enhancement, tests

#416 #386 - support oracle
  .github/workflows/oracle9i-github-publish.yml
  pom-oracle9i.xml
  pom.xml
  src/test/java/com/homihq/db2rest/rest/MySQLInnerSelfJoinControllerTest.java
Labels: enhancement

#420 #417 - fix schema filter
  pom-oracle9i.xml
  pom.xml
  src/main/java/com/homihq/db2rest/core/config/Db2RestConfigProperties.java
  src/main/resources/application.yml
Labels: bug

#423 #422 - read integration test for oracle
  src/test/java/com/homihq/db2rest/rest/oracle/OracleReadControllerTest.java
Labels: enhancement

#424 #397 - bulk create oracle
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLReadControllerTest.java
  src/test/java/com/homihq/db2rest/rest/oracle/OracleBulkCreateControllerTest.java
Labels: enhancement

#426 #425 - oracle9i release
  pom-oracle9i.xml
  pom.xml
Labels: enhancement

#433 mongodb create simple document - work in progress
  pom.xml
  src/main/java/com/homihq/db2rest/core/DbOperationService.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcCacheConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcProcessorConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcServiceConfiguration.java
  src/main/java/com/homihq/db2rest/mongodb/DefaultMongodbOperationService.java
  src/main/java/com/homihq/db2rest/mongodb/MongodbDialect.java
  src/main/java/com/homihq/db2rest/mongodb/MongodbOperationService.java
  src/main/java/com/homihq/db2rest/mongodb/config/MongodbConfiguration.java
  src/main/java/com/homihq/db2rest/mongodb/config/MongodbServiceConfiguration.java
  src/main/java/com/homihq/db2rest/mongodb/service/MongodbCreateService.java
  src/main/resources/application.yml
Labels: enhancement

#435 Feature/434 refactor mongo
  pom-oracle9i.xml
  pom.xml
  src/main/java/com/homihq/db2rest/Db2restApplication.java
  src/main/java/com/homihq/db2rest/mongo/config/MongoConfiguration.java
  src/main/java/com/homihq/db2rest/mongo/dialect/MongoDialect.java
  src/main/java/com/homihq/db2rest/mongo/repository/MongoRepository.java
  src/main/java/com/homihq/db2rest/mongo/rest/MongoController.java
  src/main/java/com/homihq/db2rest/mongo/rest/api/MongoRestApi.java
  src/main/java/com/homihq/db2rest/mongodb/MongodbOperationService.java
  src/main/java/com/homihq/db2rest/mongodb/config/MongodbConfiguration.java
  src/main/java/com/homihq/db2rest/mongodb/config/MongodbServiceConfiguration.java
  src/main/java/com/homihq/db2rest/mongodb/service/MongodbCreateService.java
  src/main/resources/application.yml
Labels: enhancement

#440 #436 - jdbc refactor
  pom-oracle9i.xml
  pom.xml
Labels: enhancement

#441 #436 - jdbc refactor
  pom-oracle9i.xml
  pom.xml
  src/main/java/com/homihq/db2rest/core/config/DataSource.java
  src/main/java/com/homihq/db2rest/jdbc/config/DataSourceConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcCacheConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcProcessorConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcServiceConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/RestApiConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/processor/RootTableProcessor.java
  src/test/java/com/homihq/db2rest/MySQLContainerConfiguration.java
  src/test/java/com/homihq/db2rest/OracleContainerConfiguration.java
  src/test/java/com/homihq/db2rest/PostgreSQLContainerConfiguration.java
  src/test/resources/application-it-mysql.yaml
  src/test/resources/application-it-oracle.yaml
  src/test/resources/application-it-pg.yaml
Labels: enhancement

#442 #430 - end point for all objects , #428 - retrieve views
  src/main/java/com/homihq/db2rest/core/model/DbTable.java
  src/main/java/com/homihq/db2rest/d1/D1SchemaCache.java
  src/main/java/com/homihq/db2rest/jdbc/JdbcSchemaCache.java
  src/main/java/com/homihq/db2rest/jdbc/config/DataSourceConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcCacheConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/rest/system/SchemaController.java
  src/main/java/com/homihq/db2rest/jdbc/rest/system/SchemaRestApi.java
  src/main/java/com/homihq/db2rest/jdbc/rest/system/TableObject.java
  src/main/java/com/homihq/db2rest/jdbc/sql/JdbcMetaDataProvider.java
  src/test/java/com/homihq/db2rest/PostgreSQLContainerConfiguration.java
Labels: bug, enhancement

#443 #365 - configurable server port
  pom-oracle9i.xml
  pom.xml
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcProcessorConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcServiceConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/config/RestApiConfiguration.java
  src/main/resources/application.yml
Labels: enhancement

#444 Feature/fix operators
  src/main/java/com/homihq/db2rest/jdbc/JdbcOperationService.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/EndWithOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/GreaterThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/GreaterThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/InOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/LessThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/LessThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/NotInOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/OperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/StartWithOperatorHandler.java
  src/main/resources/application.yml
Labels: bug, enhancement

#446 #429 - date time format customization introduced
  src/main/java/com/homihq/db2rest/core/config/DateTimeConfigProperties.java
  src/main/java/com/homihq/db2rest/core/config/DateTimeConfiguration.java
  src/main/java/com/homihq/db2rest/core/config/Db2RestConfigProperties.java
  src/main/resources/application.yml
Labels: enhancement

#449 #448 - change environment variable name
  src/main/java/com/homihq/db2rest/core/config/DateTimeConfigProperties.java
  src/main/java/com/homihq/db2rest/core/config/DateTimeConfiguration.java
  src/main/resources/application.yml
Labels: enhancement

#452 #450 - improve meta data extraction
  src/main/java/com/homihq/db2rest/jdbc/sql/JdbcMetaDataProvider.java
  src/main/java/com/homihq/db2rest/jdbc/sql/MetaDataExtraction.java
  src/main/java/com/homihq/db2rest/jdbc/sql/MetaDataTable.java
  src/main/java/com/homihq/db2rest/jdbc/sql/MySQLDataExtraction.java
  src/main/java/com/homihq/db2rest/jdbc/sql/OracleMetaDataExtraction.java
  src/main/java/com/homihq/db2rest/jdbc/sql/PostgreSQLDataExclusion.java
  src/main/java/com/homihq/db2rest/jdbc/sql/SqlCreatorTemplate.java
  src/main/resources/application.yml
Labels: enhancement

#454 Feature/451 rsql issue
  pom-oracle9i.xml
  pom.xml
  src/main/java/com/homihq/db2rest/core/Dialect.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/EndWithOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/EqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/GreaterThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/GreaterThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/InOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/LessThanEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/LessThanOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/LikeOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/NotEqualToOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/NotInOperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/OperatorHandler.java
  src/main/java/com/homihq/db2rest/jdbc/rsql/operator/handler/StartWithOperatorHandler.java
Labels: bug

#455 updated readme for 0.2.8 release
  README.md
Labels: documentation

#459 #456 - search on schema object
  pom-oracle9i.xml
  pom.xml
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/rest/schema/SchemaController.java
  src/main/java/com/homihq/db2rest/jdbc/rest/schema/SchemaRestApi.java
  src/main/java/com/homihq/db2rest/jdbc/rest/schema/TableObject.java
  src/main/java/com/homihq/db2rest/jdbc/rest/system/SchemaController.java
  src/main/java/com/homihq/db2rest/jdbc/rest/system/SchemaRestApi.java
Labels: enhancement

#462 Feature/268 refactor test data
  src/test/java/com/homihq/db2rest/rest/PgUpdateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLUpdateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/oracle/OracleBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/oracle/OracleUpdateControllerTest.java
  src/test/java/com/homihq/db2rest/rest/pg/PgBulkCreateControllerTest.java
  src/test/java/com/homihq/db2rest/utils/ITestUtil.java
  src/test/resources/testdata/BULK_CREATE_DIRECTOR_BAD_REQUEST.json
  src/test/resources/testdata/BULK_CREATE_DIRECTOR_REQUEST.json
  src/test/resources/testdata/BULK_CREATE_REVIEW_REQUEST.json
  src/test/resources/testdata/CREATE_FILM_BAD_REQUEST_CSV.csv
  src/test/resources/testdata/CREATE_FILM_REQUEST_CSV.csv
  src/test/resources/testdata/UPDATE_FILMS_REQUEST.json
  src/test/resources/testdata/UPDATE_FILM_REQUEST.json
  src/test/resources/testdata/UPDATE_NON_EXISTING_FILM_REQUEST.json
  src/test/resources/testdata/UPDATE_NON_EXISTING_TABLE.json
Labels: enhancement

#479 #478 - encapsulate dialect
  pom-oracle9i.xml
  pom.xml
  src/main/java/com/homihq/db2rest/d1/config/D1ServiceConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/JdbcSchemaCache.java
  src/main/java/com/homihq/db2rest/jdbc/config/JdbcConfiguration.java
  src/main/java/com/homihq/db2rest/jdbc/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/jdbc/processor/RootWhereProcessor.java
  src/main/java/com/homihq/db2rest/jdbc/service/JdbcBulkCreateService.java
  src/main/java/com/homihq/db2rest/jdbc/service/JdbcCreateService.java
  src/main/java/com/homihq/db2rest/jdbc/service/JdbcDeleteService.java
  src/main/java/com/homihq/db2rest/jdbc/service/JdbcUpdateService.java
  src/main/java/com/homihq/db2rest/jdbc/sql/SqlCreatorTemplate.java
Labels: enhancement

#486 #345 - postgresql join integration tests.
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLFunctionControllerTest.java
  src/test/java/com/homihq/db2rest/rest/mysql/MySQLProcedureControllerTest.java
  src/test/java/com/homihq/db2rest/rest/pg/PgBasicJoinControllerTest.java
  src/test/java/com/homihq/db2rest/rest/pg/PgCrossJoinControllerTest.java
  src/test/java/com/homihq/db2rest/rest/pg/PgDeleteControllerTest.java
  src/test/java/com/homihq/db2rest/rest/pg/PgFunctionControllerTest.java
  src/test/java/com/homihq/db2rest/rest/pg/PgProcedureControllerTest.java
  src/test/java/com/homihq/db2rest/rest/pg/PgReadControllerTest.java
  src/test/java/com/homihq/db2rest/rest/pg/PgUpdateControllerTest.java
  src/test/resources/pg/postgres-sakila-data.sql
  src/test/resources/pg/postgres-sakila.sql
  src/test/resources/testdata/CROSS_JOIN_TOPS_PG.json
  src/test/resources/testdata/CROSS_JOIN_USERS_PG.json
Labels: enhancement

#490 #489 - fix column naming issues
  src/main/java/com/homihq/db2rest/d1/D1SchemaCache.java
  src/main/java/com/homihq/db2rest/jdbc/core/model/DbColumn.java
  src/main/java/com/homihq/db2rest/jdbc/core/model/DbTable.java
  src/main/java/com/homihq/db2rest/jdbc/core/service/JdbcReadService.java
  src/main/java/com/homihq/db2rest/jdbc/sql/MySQLDataExtraction.java
  src/main/java/com/homihq/db2rest/jdbc/sql/OracleMetaDataExtraction.java
  src/main/java/com/homihq/db2rest/jdbc/sql/PostgreSQLDataExclusion.java
Labels: enhancement

#492 #491 : d1 removed
  README.md
  src/main/java/com/homihq/db2rest/d1/D1Dialect.java
  src/main/java/com/homihq/db2rest/d1/D1OperationService.java
  src/main/java/com/homihq/db2rest/d1/D1RestClient.java
  src/main/java/com/homihq/db2rest/d1/D1SchemaCache.java
  src/main/java/com/homihq/db2rest/d1/config/D1Configuration.java
  src/main/java/com/homihq/db2rest/d1/config/D1ServiceConfiguration.java
  src/main/java/com/homihq/db2rest/d1/model/D1Column.java
  src/main/java/com/homihq/db2rest/d1/model/D1PostRequest.java
  src/main/java/com/homihq/db2rest/d1/model/D1PostResponse.java
  src/main/java/com/homihq/db2rest/d1/model/D1Result.java
  src/main/java/com/homihq/db2rest/d1/model/D1Table.java
  src/main/java/com/homihq/db2rest/d1/model/Message.java
  src/main/java/com/homihq/db2rest/d1/service/D1FunctionService.java
  src/main/java/com/homihq/db2rest/d1/service/D1ProcedureService.java
Labels: enhancement

#495 #494 : new ssl factory class added.
  pom-oracle9i.xml
  pom.xml
  src/main/java/com/homihq/db2rest/jdbc/driver/PgSingleCertValidatingFactory.java
Labels: enhancement

#498 integration tests with mongodb testcontainer
  pom.xml
  src/test/java/com/homihq/db2rest/MongodbContainerConfiguration.java
  src/test/java/com/homihq/db2rest/rest/mongo/MongoControllerTest.java
  src/test/resources/application-it-mongo.yaml
  src/test/resources/mongo/mongo-sakila.js
  src/test/resources/testdata/CREATE_ACTOR_REQUEST.json
Labels: enhancement

#511 Feature/497 query table with same name diff schema
  src/main/java/com/homihq/db2rest/jdbc/JdbcSchemaCache.java
  src/main/java/com/homihq/db2rest/jdbc/core/schema/AliasGenerator.java
  src/main/java/com/homihq/db2rest/jdbc/core/service/JdbcBulkCreateService.java
  src/main/java/com/homihq/db2rest/jdbc/core/service/JdbcCreateService.java
  src/main/java/com/homihq/db2rest/jdbc/core/service/JdbcDeleteService.java
  src/main/java/com/homihq/db2rest/jdbc/core/service/JdbcUpdateService.java
  src/main/java/com/homihq/db2rest/jdbc/processor/JoinProcessor.java
  src/main/java/com/homihq/db2rest/jdbc/processor/RootTableProcessor.java
  src/main/java/com/homihq/db2rest/jdbc/rest/delete/DeleteController.java
  src/main/java/com/homihq/db2rest/jdbc/rest/delete/DeleteRestApi.java
  src/main/java/com/homihq/db2rest/jdbc/rest/read/CountQueryController.java
  src/main/java/com/homihq/db2rest/jdbc/rest/read/ExistsQueryController.java
  src/main/java/com/homihq/db2rest/jdbc/rest/read/FindOneController.java
  src/main/java/com/homihq/db2rest/jdbc/rest/read/ReadController.java
  src/main/java/com/homihq/db2rest/jdbc/rest/read/dto/JoinDetail.java
  src/main/java/com/homihq/db2rest/jdbc/rest/read/dto/ReadContext.java
  src/test/java/com/homihq/db2rest/MySQLContainerConfiguration.java
  src/test/java/com/homihq/db2rest/rest/mysql/CountTwoTablesSameNameDiffSchemaTest.java
  src/test/java/com/homihq/db2rest/rest/mysql/CreateTwoTablesSameNameDiffSchemaTest.java
  src/test/java/com/homihq/db2rest/rest/mysql/DeleteTwoTablesSameNameDiffSchemaTest.java
  src/test/java/com/homihq/db2rest/rest/mysql/ReadTwoTablesSameNameDiffSchemaTest.java
  src/test/java/com/homihq/db2rest/rest/mysql/UpdateTwoTablesSameNameDiffSchemaTest.java
  src/test/resources/mysql/mysql-sakila-data.sql
  src/test/resources/mysql/mysql-sakila.sql
  src/test/resources/mysql/mysql-wakila-all.sql
  src/test/resources/testdata/CREATE_EMP_REQUEST.json
  src/test/resources/testdata/UPDATE_EMPLOYEE_REQUEST.json
Labels: enhancement

#513 #512 - upgrade to spring boot 3.2.5
  pom-oracle9i.xml
  pom.xml
Labels: enhancement

#514 hot fix 0.3.1
  pom-oracle9i.xml
  pom.xml
Labels: bug

#518 Feature/510 update exception
  api-rest/pom.xml
  api-rest/src/main/java/com/homihq/db2rest/bulk/CSVDataProcessor.java
  api-rest/src/main/java/com/homihq/db2rest/bulk/DataProcessor.java
  api-rest/src/main/java/com/homihq/db2rest/bulk/JSONDataProcessor.java
  api-rest/src/main/java/com/homihq/db2rest/config/DateTimeConfigProperties.java
  api-rest/src/main/java/com/homihq/db2rest/config/DateTimeConfiguration.java
  api-rest/src/main/java/com/homihq/db2rest/config/Db2RestConfigProperties.java
  api-rest/src/main/java/com/homihq/db2rest/config/MultiTenancy.java
  api-rest/src/main/java/com/homihq/db2rest/config/OpenAPIConfiguration.java
  api-rest/src/main/java/com/homihq/db2rest/config/TenancyMode.java
  api-rest/src/main/java/com/homihq/db2rest/config/ThymeleafConfiguration.java
  api-rest/src/main/java/com/homihq/db2rest/core/exception/AuthenticationFailedException.java
  api-rest/src/main/java/com/homihq/db2rest/core/exception/DeleteOpNotAllowedException.java
  api-rest/src/main/java/com/homihq/db2rest/core/exception/GenericDataAccessException.java
  api-rest/src/main/java/com/homihq/db2rest/core/exception/GlobalExceptionHandler.java
  api-rest/src/main/java/com/homihq/db2rest/core/exception/InvalidColumnException.java
  api-rest/src/main/java/com/homihq/db2rest/core/exception/InvalidOperatorException.java
  api-rest/src/main/java/com/homihq/db2rest/core/exception/InvalidSchemaException.java
  api-rest/src/main/java/com/homihq/db2rest/core/exception/InvalidTableException.java
  api-rest/src/main/java/com/homihq/db2rest/core/exception/MissingAuthenticationException.java
  api-rest/src/main/java/com/homihq/db2rest/core/exception/RpcException.java
  api-rest/src/main/java/com/homihq/db2rest/exception/GlobalExceptionHandler.java
  api-rest/src/main/java/com/homihq/db2rest/jdbc/JdbcSchemaCache.java
  api-rest/src/main/java/com/homihq/db2rest/jdbc/config/JdbcConfiguration.java
  api-rest/src/main/java/com/homihq/db2rest/jdbc/core/service/JdbcDeleteService.java
  api-rest/src/main/java/com/homihq/db2rest/jdbc/dialect/MySQLDialect.java
  api-rest/src/main/java/com/homihq/db2rest/jdbc/dialect/OracleDialect.java
  api-rest/src/main/java/com/homihq/db2rest/jdbc/dialect/PostGreSQLDialect.java
  api-rest/src/main/java/com/homihq/db2rest/jdbc/rest/create/BulkCreateController.java
  api-rest/src/main/java/com/homihq/db2rest/jdbc/sql/JdbcMetaDataProvider.java
  api-rest/src/main/java/com/homihq/db2rest/jdbc/sql/SqlCreatorTemplate.java
  api-rest/src/main/java/com/homihq/db2rest/mongo/config/MongoConfiguration.java
  api-rest/src/main/java/com/homihq/db2rest/mongo/rest/MongoController.java
  db2rest-common/.gitignore
  db2rest-common/.mvn/wrapper/maven-wrapper.jar
  db2rest-common/.mvn/wrapper/maven-wrapper.properties
  db2rest-common/mvnw
  db2rest-common/mvnw.cmd
  db2rest-common/pom.xml
  db2rest-common/src/main/java/com/homihq/db2rest/core/dto/CreateBulkResponse.java
  db2rest-common/src/main/java/com/homihq/db2rest/core/dto/CreateResponse.java
  db2rest-common/src/main/java/com/homihq/db2rest/core/dto/DeleteResponse.java
  db2rest-common/src/main/java/com/homihq/db2rest/core/exception/AuthenticationFailedException.java
  db2rest-common/src/main/java/com/homihq/db2rest/core/exception/DeleteOpNotAllowedException.java
  db2rest-common/src/main/java/com/homihq/db2rest/core/exception/GenericDataAccessException.java
  db2rest-common/src/main/java/com/homihq/db2rest/core/exception/InvalidColumnException.java
  db2rest-common/src/main/java/com/homihq/db2rest/core/exception/InvalidOperatorException.java
  db2rest-common/src/main/java/com/homihq/db2rest/core/exception/InvalidTableException.java
  db2rest-common/src/main/java/com/homihq/db2rest/core/exception/RpcException.java
  pom.xml
Labels: documentation
